**Pontia Tech - Master Data Analytics - Visualización de Datos con Python**

Datos del alumno (Nombre y Apellidos): Gilberto Noguera

Fecha: 20/04

<span style="font-size: 30pt; font-weight: bold; color: #0098cd;">Estudio Politica Descuentos Pontia SuperStore</span>

<span style="font-size: 15pt; font-weight: bold; color: #0098cd;">Sesión Live Práctica</span>

Entregable Visualización Python

**Objetivos**

El objetivo de este caso práctico es realizar un estudio de como ha impactado la politica de descuentos a la rentabilidad de la empresa Pontia SuperStore. Para ello usaremos la librería Plotly para la elaboración de gráficos Interactivos.

**Enunciado**

Somos parte del equipo de datos de la empresa PontiaSuperStore han encargado hacer un estudio de cómo ha impactado la politica de descuentos en la rentabilidad de la empresa.

Para ello contamos con un dataset con los pedidos efectuados a la empresa. En cada pedido hay una columna que nos informa del % de descuento que lleva esa venta asociada. ¿Esta afectando a la rentabilidad de la empresa? ¿Es igual para todos los productos?

Elabora un reporte usando python que contenga diferentes visualizaciones ilustrando el problema.

Trata de no pensar directamente en la solución y construye una historia a traves de los datos.

**Requisitos de la actividad:**

1º El reporte debe contener mínimo tres visualizaciones. Recomendación: Es interesante pensar en una estructura introducción - nudo - desenlace. En la que se presenta el problema primero, se aportan diferentes puntos de vista y se da una solución.

2º Utilización de Plotly para resolver el ejercicio.

3º Entregar el Notebook con las respuestas argumentadas, no solo el gráfico.

<span style="font-size: 20pt; font-weight: bold; color: #0098cd;">1. Importación Librerías y Carga Datos</span>

<span style="font-size: 15pt; font-weight: bold; color: #0098cd;">1.1. Importación Librerías</span>

In [1]:
# Librerías Procesamiento de Datos.
import pandas as pd
import numpy as np

# Librería de Visualización
import plotly.express as px

# Avoid Warnings
import warnings #Para que python maneje advertenvia  (warning)
warnings.filterwarnings('ignore') # ignora todos los warning

In [ ]:
%matplotlib inline
"""Le dice a Jupyter Notebook: Cada vez que generes un grafico con Matplotib, muestrame driectamete dentro de la celda, incrustado en el notebook"""

'Le dice a Jupyter Notebook: Cada vez que generes un grafico con Matplotib, muestrame driectamete dentro de la celda, incrustado en el notebook'

**¿Por que es util?**
- Podria abrir los graficos en una ventana externa
- No mostrar nada
- Mostrarlo de froma inconsistetente

**Con %matplotlib online**
- Los grafico s aparecen justo debajo del codigo
- Quedan guradados en el notebook
- Puedes exportarlos junto con el análisis

# <span style="font-size: 15pt; font-weight: bold; color: #0098cd;">1.2. Carga de Datos</span>

La carga de los datos la podemos hacer en Colab usando la librería "io" o en local.

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
import io
df = pd.read_excel('/content/drive/MyDrive/Master con Pontia /visualizacion de datos/Visualización de datos - DA-20260414T123648Z-3-001/Visualización de datos - DA/Visualización Python/Live/Practica/Dataset/PontiaSuperStore.xls')
df.head(3)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.62,2,0.0,6.8714

#Analisis Estadisticos

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   datetime64[ns]
 3   Ship Date      9994 non-null   datetime64[ns]
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 1.6+ MB

In [94]:
valores_nulos = df.isnull().sum()
print(valores_nulos)

Row ID             0
Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name      0
Segment            0
Country            0
City               0
State              0
Postal Code        0
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name       0
Sales              0
Quantity           0
Discount           0
Profit             0
price_per_unit     0
profit_per_unit    0
flag_descuento     0
Year               0
dtype: int64

In [29]:
df.describe() #Resumen estadistico

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2016-04-30 00:07:12.259355648,2016-05-03 23:06:58.571142912,55190.379428,229.858001,3.789574,0.156203,28.656896
min,1.000000,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000
std,2885.163629,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108

In [44]:
df.describe(include='object')
#count = Numero de valores no nulos
#unique = Cuentos valores distintos/unicos existen en esa columna
#top = EL valor que mas veces aparece
#fred = Cuantas veces se repite ese valor mas común

,Order ID,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name
count,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994
unique,5009,4,793,793,3,1,531,49,4,1862,3,17,1850
top,CA-2017-100111,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,California,West,OFF-PA-10001970,Office Supplies,Binders,Staple envelope
freq,14,5968,37,37,5191,9994,915,2001,3203,19,6026,1523,48

In [45]:
#Ejemplo para confirmar "top"
df['City'].value_counts().head(2)

City
New York City    915
Los Angeles      747
Name: count, dtype: int64

In [48]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [50]:
df.tail(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9992,9993,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.60,4,0.0,13.320
9993,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.16,2,0.0,72.948

#Ejercicio

<span style="font-size: 15pt; font-weight: bold; color: #0098cd;">1.3. Generación de variables calculadas.</span>

Genere a partir del dataframe cargado las siguientes variables calculadas.

- Sales/Quantity: Precio de Venta por unidad de producto en cada operación de venta
- Profit/Quantity: Beneficio por unidad de producto en cada operación de venta
- flag_descuento: Marca con "Con Descuento" si esa operacion de venta ha tenido descuento (esto es descuento>0), "Sin Descuento" si no.
- Year: Variable con el año de la fecha de la operación de venta.

Respuesta:

In [54]:
"""Precio de ventas por unidad de producto en cada operacion de venta"""
# 1.Precio de Venta por unidad de producto en cada operación de venta
df["price_per_unit"]= df['Sales']/df["Quantity"]

In [55]:
# 2. Beneficio por unidad de producto en cada operación de venta
df['profit_per_unit'] = df['Profit'] / df['Quantity']

In [56]:
# 3.  Marca con "Con Descuento" si esa operacion de venta ha tenido descuento (esto es descuento>0), "Sin Descuento" si no.
df['flag_descuento'] = df['Discount'].map(lambda x: "Con Descuento" if x > 0 else "Sin Descuento")

In [59]:
df['flag_descuento'].value_counts(normalize=True)

flag_descuento
Con Descuento    0.519912
Sin Descuento    0.480088
Name: proportion, dtype: float64

In [57]:
# 4.Variable con el año de la fecha de la operación de venta.
# Primero nos aseguramos de que 'Order Date' sea de tipo datetime.
# Si los datos provienen de Excel y aparecen como números (ej. 42682.0), usamos origin='1899-12-30'
df['Year'] = df['Order Date'].dt.year

<span style="font-size: 20pt; font-weight: bold; color: #0098cd;">2. Estudio Descuentos PontiaSuperStore</span>

Elaboración del reporte.

Argumenta y explica la motivación del gráfico así como sus enunciados.

# <span style="font-size: 15pt; font-weight: bold; color: #0098cd;">2.1. Gráfico 1.</span>

Respuesta:

In [ ]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit',
       'price_per_unit', 'profit_per_unit', 'flag_descuento', 'Year'],
      dtype='object')

In [78]:
import plotly.express as px

# 1. Agrupamos los datos para obtener el promedio anual por tipo de descuento
df_plot = df.groupby(['Year', 'flag_descuento'])['profit_per_unit'].mean().reset_index()

# 2. Creamos el gráfico interactivo
fig = px.line(df_plot,
              x='Year',
              y='profit_per_unit',
              color='flag_descuento',
              markers=True,
              title='Análisis Histórico: Beneficio Unitario vs Estrategia de Descuento',
              labels={'profit_per_unit': 'Beneficio Medio por Unidad ($)',
                      'Year': 'Año de la Operación',
                      'flag_descuento': 'Estado de Venta'
              },
              template='plotly_white')

# Mejoramos el eje X para que solo muestre años enteros
fig.update_layout(xaxis_type='category')

## Analisis:
**la linea roja **nos muestra la ventas sin descuento, demostrando estalabilidad, rondando un beneficio medio por unidad entre 18,43 para el 2015 y 17,26 para el 2016.

**linea azul:** Esta linea esta situada en eje y de los numero negativos indicando peligro, esta entre -1 y -2

### Conclusion:

La empresa pierde dinero cada vez que se aplica un descuento, no gana menos margen, si no que el beneficio por unidad vendida es negiva, costandole dinero a la empresa.

Ambas líneas son prácticamente paralelas a lo largo del tiempo. Esto significa que no es un error de un año puntual. Es un comportamiento del modelo de negocio que se ha repetido de forma idéntica desde 2014 hasta 2017. La política de descuentos está mal diseñada desde el origen.

# <span style="font-size: 15pt; font-weight: bold; color: #0098cd;">2.2. Gráfico 2.</span>

In [109]:
df_counts = df["flag_descuento"].value_counts().reset_index()
df_counts.columns = ['Tipo de Descuento', 'Conteo']

print("Cambiamos nombres de las columnas:")
print(df_counts)

fig_descuento_conteo = px.bar(
    df_counts,
    x='Tipo de Descuento',
    y='Conteo',
    title='Distribución de Transacciones por Tipo de Descuento',
    labels={'Tipo de Descuento': 'Tipo de Descuento', 'Conteo': 'Número de Transacciones'},
    orientation= 'v',
    color='Tipo de Descuento', # Diferenciar las barras por color
    color_discrete_map= {'Con Descuento' : 'goldenrod', 'Sin Descuento':'magenta'}
)
fig_descuento_conteo.update_layout(xaxis_title='Tipo de Descuento', yaxis_title='Número de Transacciones')


fig_descuento_conteo.show()

Cambiamos nombres de las columnas:
  Tipo de Descuento  Conteo
0     Con Descuento    5196
1     Sin Descuento    4798

## Analisis:
Las transaccines con descuento superan las 5.000 operaciones. Por el contrario, la ventas a precio sin descuento rondean las 4.8000

### Coclusiones:
La empresa tiene una fuga de dinero porque su actividad principal esta operando a perdidas extrordinarias. Estas vendiendo mas de los que mas, pero con un beneficio negativo.

# <span style="font-size: 15pt; font-weight: bold; color: #0098cd;">2.3. Gráfico 3.</span>

In [147]:
import plotly.express as px

# Análisis del beneficio medio por nivel de descuento
df_disc = df.groupby('Discount')['Profit'].mean().reset_index()
print(df_disc)
fig = px.scatter(df, x='Discount', y='Profit',
             color='Profit',
             color_continuous_scale='Viridis',
             title='Análisis Crítico: ¿A qué nivel de descuento empezamos a perder?',
             labels={'Profit': 'Beneficio Medio ($)', 'Discount': 'Nivel de Descuento (%)'},
             template='plotly_white')

# Añadimos una línea en el 0 para marcar el umbral de pérdida
fig.add_hline(y=0, line_dash="dash", line_color="black")
fig.show()

    Discount      Profit
0       0.00   66.900292
1       0.10   96.055074
2       0.15   27.288298
3       0.20   24.702572
4       0.30  -45.679636
5       0.32  -88.560656
6       0.40 -111.927429
7       0.45 -226.646464
8       0.50 -310.703456
9       0.60  -43.077212
10      0.70  -95.874060
11      0.80 -101.796797

#Analisis y concluion:
El gráfico de dispersión demuestra con precisión que el impacto de los descuentos no es lineal: mientras que el rango del 0% al 20% asegura márgenes positivos, el nivel del 30% actúa como un punto de inflexión inestable donde coexisten ventas rentables con pérdidas. A partir del 40%, la nube de puntos se desplaza exclusivamente hacia el cuadrante inferior, eliminando cualquier posibilidad de beneficio y revelando pérdidas extremas por transacción. Este análisis transaccional confirma la urgencia de implementar un bloqueo informático estricto en el sistema de facturación a partir del 40% de descuento para detener la fuga masiva de capital.

<span style="font-size: 20pt; font-weight: bold; color: #0098cd;">3. Guardado del Trabajo.</span>

Exportando una gráfica.

In [164]:
fig3.write_html("regresion_descuentos.html")

Transformando nuestro Notebook en un Reporting.

In [166]:
!jupyter nbconvert --to html PontiaSuperStore.ipynb --no-input

[NbConvertApp] WARNING | pattern 'PontiaSuperStore.ipynb' matched no files
This application is used to convert notebook files (*.ipynb)
        to various other formats.

        WARNING: THE COMMANDLINE INTERFACE MAY CHANGE IN FUTURE RELEASES.

Options
=======
The options below are convenience aliases to configurable class-options,
as listed in the "Equivalent to" description-line of the aliases.
To see all configurable class-options for some <cmd>, use:
    <cmd> --help-all

--debug
    set log level to logging.DEBUG (maximize logging output)
    Equivalent to: [--Application.log_level=10]
--show-config
    Show the application's configuration (human-readable format)
    Equivalent to: [--Application.show_config=True]
--show-config-json
    Show the application's configuration (json format)
    Equivalent to: [--Application.show_config_json=True]
--generate-config
    generate default config file
    Equivalent to: [--JupyterApp.generate_config=True]
-y
    Answer yes to any questions instead of prompting.
    Equivalent to: [--JupyterApp.answer_yes=True]
--execute
    Execute the notebook prior to export.
    Equivalent to: [--ExecutePreprocessor.enabled=True]
--allow-errors
    Continue notebook execution even if one of the cells throws an error and include the error message in the cell output (the default behaviour is to abort conversion). This flag is only relevant if '--execute' was specified, too.
    Equivalent to: [--ExecutePreprocessor.allow_errors=True]
--stdin
    read a single notebook file from stdin. Write the resulting notebook with default basename 'notebook.*'
    Equivalent to: [--NbConvertApp.from_stdin=True]
--stdout
    Write notebook output to stdout instead of files.
    Equivalent to: [--NbConvertApp.writer_class=StdoutWriter]
--inplace
    Run nbconvert in place, overwriting the existing notebook (only
            relevant when converting to notebook format)
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory=]
--clear-output
    Clear output of current file and save in place,
            overwriting the existing notebook.
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory= --ClearOutputPreprocessor.enabled=True]
--coalesce-streams
    Coalesce consecutive stdout and stderr outputs into one stream (within each cell).
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory= --CoalesceStreamsPreprocessor.enabled=True]
--no-prompt
    Exclude input and output prompts from converted document.
    Equivalent to: [--TemplateExporter.exclude_input_prompt=True --TemplateExporter.exclude_output_prompt=True]
--no-input
    Exclude input cells and output prompts from converted document.
            This mode is ideal for generating code-free reports.
    Equivalent to: [--TemplateExporter.exclude_output_prompt=True --TemplateExporter.exclude_input=True --TemplateExporter.exclude_input_prompt=True]
--allow-chromium-download
    Whether to allow downloading chromium if no suitable version is found on the system.
    Equivalent to: [--WebPDFExporter.allow_chromium_download=True]
--disable-chromium-sandbox
    Disable chromium security sandbox when converting to PDF..
    Equivalent to: [--WebPDFExporter.disable_sandbox=True]
--show-input
    Shows code input. This flag is only useful for dejavu users.
    Equivalent to: [--TemplateExporter.exclude_input=False]
--embed-images
    Embed the images as base64 dataurls in the output. This flag is only useful for the HTML/WebPDF/Slides exports.
    Equivalent to: [--HTMLExporter.embed_images=True]
--sanitize-html
    Whether the HTML in Markdown cells and cell outputs should be sanitized..
    Equivalent to: [--HTMLExporter.sanitize_html=True]
--log-level=<Enum>
    Set the log level by value or name.
    Choices: any of [0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL']
    Default: 30
    Equivalent to: [--Application.log_level]
--config=<Unicode>
    Full path of a config file.
    Default: ''
    Equivalent to: [--JupyterApp.config_file]
--to=<Unicode>
    The export format to be used, either one of the built-in formats
            ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'qtpdf', 'qtpng', 'rst', 'script', 'slides', 'webpdf']
            or a dotted object name that represents the import path for an
            ``Exporter`` class
    Default: ''
    Equivalent to: [--NbConvertApp.export_format]
--template=<Unicode>
    Name of the template to use
    Default: ''
    Equivalent to: [--TemplateExporter.template_name]
--template-file=<Unicode>
    Name of the template file to use
    Default: None
    Equivalent to: [--TemplateExporter.template_file]
--theme=<Unicode>
    Template specific theme(e.g. the name of a JupyterLab CSS theme distributed
    as prebuilt extension for the lab template)
    Default: 'light'
    Equivalent to: [--HTMLExporter.theme]
--sanitize_html=<Bool>
    Whether the HTML in Markdown cells and cell outputs should be sanitized.This
    should be set to True by nbviewer or similar tools.
    Default: False
    Equivalent to: [--HTMLExporter.sanitize_html]
--writer=<DottedObjectName>
    Writer class used to write the
                                        results of the conversion
    Default: 'FilesWriter'
    Equivalent to: [--NbConvertApp.writer_class]
--post=<DottedOrNone>
    PostProcessor class used to write the
                                        results of the conversion
    Default: ''
    Equivalent to: [--NbConvertApp.postprocessor_class]
--output=<Unicode>
    Overwrite base name use for output files.
                Supports pattern replacements '{notebook_name}'.
    Default: '{notebook_name}'
    Equivalent to: [--NbConvertApp.output_base]
--output-dir=<Unicode>
    Directory to write output(s) to. Defaults
                                  to output to the directory of each notebook. To recover
                                  previous default behaviour (outputting to the current
                                  working directory) use . as the flag value.
    Default: ''
    Equivalent to: [--FilesWriter.build_directory]
--reveal-prefix=<Unicode>
    The URL prefix for reveal.js (version 3.x).
            This defaults to the reveal CDN, but can be any url pointing to a copy
            of reveal.js.
            For speaker notes to work, this must be a relative path to a local
            copy of reveal.js: e.g., "reveal.js".
            If a relative path is given, it must be a subdirectory of the
            current directory (from which the server is run).
            See the usage documentation
            (https://nbconvert.readthedocs.io/en/latest/usage.html#reveal-js-html-slideshow)
            for more details.
    Default: ''
    Equivalent to: [--SlidesExporter.reveal_url_prefix]
--nbformat=<Enum>
    The nbformat version to write.
            Use this to downgrade notebooks.
    Choices: any of [1, 2, 3, 4]
    Default: 4
    Equivalent to: [--NotebookExporter.nbformat_version]

Examples
--------

    The simplest way to use nbconvert is

            > jupyter nbconvert mynotebook.ipynb --to html

            Options include ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'qtpdf', 'qtpng', 'rst', 'script', 'slides', 'webpdf'].

            > jupyter nbconvert --to latex mynotebook.ipynb

            Both HTML and LaTeX support multiple output templates. LaTeX includes
            'base', 'article' and 'report'.  HTML includes 'basic', 'lab' and
            'classic'. You can specify the flavor of the format used.

            > jupyter nbconvert --to html --template lab mynotebook.ipynb

            You can also pipe the output to stdout, rather than a file

            > jupyter nbconvert mynotebook.ipynb --stdout

            PDF is generated via latex

            > jupyter nbconvert mynotebook.ipynb --to pdf

            You can get (and serve) a Reveal.js-powered slideshow

            > jupyter nbconvert myslides.ipynb --to slides --post serve

            Multiple notebooks can be given at the command line in a couple of
            different ways:

            > jupyter nbconvert notebook*.ipynb
            > jupyter nbconvert notebook1.ipynb notebook2.ipynb

            or you can specify the notebooks list in a config file, containing::

                c.NbConvertApp.notebooks = ["my_notebook.ipynb"]

            > jupyter nbconvert --config mycfg.py

To see all available configurables, use `--help-all`.